# Generated by Django 4.1.1 on 2022-09-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('icon', models.TextField(null=True)),
            ],
        ),
    ]
