# Generated by Django 4.1.1 on 2022-09-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
    ]
