# Generated by Django 4.1.1 on 2022-09-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('subtitle', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='img/%y')),
                ('link', models.TextField(null=True)),
            ],
        ),
    ]
