# Generated by Django 4.1.1 on 2022-09-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
