# Generated by Django 4.1.1 on 2022-09-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_portfolio_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
    ]
